[tool.poetry]
name = "project-3"
version = "0.1.0"
description = ""
authors = ["Pavel Artiev <arijev@bk.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
